[functions.auth-otp]
verify_jwt = false

[functions.process-document]
verify_jwt = true

[functions.generate-invoice]
verify_jwt = true

[functions.semantic-search]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[auth]
enabled = true
jwt_expiry = 604800
enable_refresh_token_rotation = true
enable_signup = true
enable_anonymous_sign_ins = false


[auth.sms]
enable_signup = true
enable_confirmations = true
template = "Your code is {{ .Code }}"


##############################################
#   Twilio SMS Provider
##############################################
[auth.sms.twilio]
enabled = true

# Read from your .env file â€” recommended
account_sid = "AC58a75779208719925658587f31606f0e"
auth_token  = "9976364f3771e40160755f4823186d2c"

# Twilio phone number purchased from the console
message_service_sid= "MG16765865102700812768710017124889"

[auth.sms.test_otp]
"+11234567890" = "123456"

